apiVersion: v1
kind: ReplicationController
metadata:
  name: rahulrc-1
spec:
  replicas: 1 # Number of pod we want first
  template:
    metadata:
      labels:
        x: hellorahulapp
    spec:
      imagePullSecrets:
        - name: rahulsec11
      containers: 
      - name: rahulc-1
        image: phx.ocir.io/axmbtg8judkl/webapp:v1
        ports: 
        - containerPort: 80