apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rahulsvc
  name: rahulsvc
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: rahulsvc
  type: LoadBalancer
status:
  loadBalancer: {}
