apiVersion: v1
kind: ReplicationController
metadata:
  name: rahulrc-1
spec:
  replicas: 1 # Number of pod we want first
  template:
    metadata:
      labels:
        x: hellorahulapp
    spec:
      containers: 
      - name: rahulc-1
        image: dockerashu/nginx:5thoct2021
        ports: 
        - containerPort: 80
